# Configuração Netlify para Next.js
[build]
  # Comandos de build do Next.js
  command = "npm run build"
  publish = ".next"
  
# Plugin Next.js - necessário para SSR e API routes funcionarem
[[plugins]]
  package = "@netlify/plugin-nextjs"


# Headers de segurança
[[headers]]
  for = "/api/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"

# Headers para imagens
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

# Bloquear acesso direto a arquivos HTML originais
[[redirects]]
  from = "/index.html"
  to = "/404"
  status = 404

[[redirects]]
  from = "/agradecimento.html"
  to = "/404"
  status = 404

[[redirects]]
  from = "/remarketing.html"
  to = "/404"
  status = 404

[[redirects]]
  from = "/links-rastreamento.html"
  to = "/404"
  status = 404

# Variáveis de ambiente (valores padrão)
[build.environment]
  NEXT_PUBLIC_BASE_URL = "https://marmari.netlify.app"

